# This is a basic workflow to help you get started with Actions

name: Build images

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ ci-test ]
#  pull_request:
#    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buster_armhf:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Install needed packagest
      run: |
        sudo apt-get install python3-cliapp cmdtest debootstrap qemu-utils kpartx qemu-user-static binfmt-support zerofree lbzip2

    - name: Install vmdb2
      run: |
        wget http://ftp.de.debian.org/debian/pool/main/v/vmdb2/vmdb2_0.14.1-1_all.deb
        sudo dpkg -i vmdb2_0.14.1-1_all.deb

    - name: Build Cubietruck
      run: sudo vmdb2 cubietruck_buster_armhf_vmdb2-0.14.1.yaml --output cubietruck_buster_armhf.img --rootfs-tarball buster_armhf_rootfs.tgz --log=stderr

    - name: Zero-ing obsolete data blocks
      run: loopN=$(sudo kpartx -asv cubietruck_buster_armhf.img | cut -d\  -f 3); sudo zerofree /dev/mapper/$loopN; sudo kpartx -dsv cubietruck_buster_armhf.img

    - name: Compress image
      run: sudo lbzip2 cubietruck_buster_armhf.img

    - uses: actions/upload-artifact@v1
      with:
        name: cubietruck_buster_armhf.img.bz2
        path: cubietruck_buster_armhf.img.bz2

    - name: Build Cubietruck Plus
      run: sudo vmdb2 cubietruck-plus_buster_armhf_vmdb2-0.14.1.yaml --output cubietruck-plus_buster_armhf.img --rootfs-tarball buster_armhf_rootfs.tgz --log=stderr

    - name: Zero-ing obsolete data blocks
      run: loopN=$(sudo kpartx -asv cubietruck-plus_buster_armhf.img | cut -d\  -f 3); sudo zerofree /dev/mapper/$loopN; sudo kpartx -dsv cubietruck-plus_buster_armhf.img

    - name: Compress image
      run: sudo lbzip2 cubietruck-plus_buster_armhf.img

    - uses: actions/upload-artifact@v1
      with:
        name: cubietruck-plus_buster_armhf.img.bz2
        path: cubietruck-plus_buster_armhf.img.bz2

    - name: Build OrangePi R1
      run: sudo vmdb2 orangepi-r1_buster_armhf_vmdb2-0.14.1.yaml --output orangepi-r1_buster_armhf.img --rootfs-tarball buster_armhf_rootfs.tgz --log=stderr

    - name: Zero-ing obsolete data blocks
      run: loopN=$(sudo kpartx -asv orangepi-r1_buster_armhf.img | cut -d\  -f 3); sudo zerofree /dev/mapper/$loopN; sudo kpartx -dsv orangepi-r1_buster_armhf.img

    - name: Compress image
      run: sudo lbzip2 orangepi-r1_buster_armhf.img

    - uses: actions/upload-artifact@v1
      with:
        name: orangepi-r1_buster_armhf.img.bz2
        path: orangepi-r1_buster_armhf.img.bz2

  buster_arm64:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Install needed packagest
      run: |
        sudo apt-get install python3-cliapp cmdtest debootstrap qemu-utils kpartx qemu-user-static binfmt-support zerofree lbzip2

    - name: Install vmdb2
      run: |
        wget http://ftp.de.debian.org/debian/pool/main/v/vmdb2/vmdb2_0.14.1-1_all.deb
        sudo dpkg -i vmdb2_0.14.1-1_all.deb

    - name: Build Rock64
      run: sudo vmdb2 rock64_buster_arm64_vmdb2-0.14.1.yaml --output rock64_buster_arm64.img --rootfs-tarball buster_arm64_rootfs.tgz --log=stderr

    - name: Zero-ing obsolete data blocks
      run: loopN=$(sudo kpartx -asv rock64_buster_arm64.img | cut -d\  -f 3); sudo zerofree /dev/mapper/$loopN; sudo kpartx -dsv rock64_buster_arm64.img

    - name: Compress image
      run: sudo lbzip2 rock64_buster_arm64.img

    - uses: actions/upload-artifact@v1
      with:
        name: rock64_buster_arm64.img.bz2
        path: rock64_buster_arm64.img.bz2

  bullseye_armhf:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Install needed packagest
      run: |
        sudo apt-get install python3-cliapp cmdtest debootstrap qemu-utils kpartx qemu-user-static binfmt-support zerofree lbzip2

    - name: Install vmdb2
      run: |
        wget http://ftp.de.debian.org/debian/pool/main/v/vmdb2/vmdb2_0.14.1-1_all.deb
        sudo dpkg -i vmdb2_0.14.1-1_all.deb

    - name: Build Cubietruck Plus
      run: sudo vmdb2 cubietruck-plus_bullseye_armhf_vmdb2-0.14.1.yaml --output cubietruck-plus_bullseye_armhf.img --rootfs-tarball bullseye_armhf_rootfs.tgz --log=stderr

    - name: Zero-ing obsolete data blocks
      run: loopN=$(sudo kpartx -asv cubietruck-plus_bullseye_armhf.img | cut -d\  -f 3); sudo zerofree /dev/mapper/$loopN; sudo kpartx -dsv cubietruck-plus_bullseye_armhf.img

    - name: Compress image
      run: sudo lbzip2 cubietruck-plus_bullseye_armhf.img

    - uses: actions/upload-artifact@v1
      with:
        name: cubietruck-plus_bullseye_armhf.img.bz2
        path: cubietruck-plus_bullseye_armhf.img.bz2
